### ISSUE TITLE
Add .zip extension in the opks :-)

### ISSUE THREAD

**Issue by CalebCDE** [eduardofilo/RG350_ra_installer#1]
Hola Eduardo, 

Te pongo esto aquí a modo de recordatorio, para la próxima versión porfa, podrías añadir .zip a todos los emuladores? :-) No tengo las roms en 7z si no en zip y con cada actualización hay que modificarlo todo jejeje

Un abrazo y gracias!!

**Comment by eduardofilo** [comment]
Tenía apuntado hacerlo en el checklist de las imágenes code animal y se me pasó hacerlo aquí. Fallo mío. Lo hago ahora y así no se me pasa.

**Comment by eduardofilo** [comment]
Fixed with 3931ab2aab99839180281b1031d8042ec226cfd6
