### ISSUE TITLE
(Request) Sega SG-1000 .OPK wrapper

### ISSUE THREAD

**Issue by litaniast** [eduardofilo/RG350_ra_installer#3]
Genesis Plus GX can emulate Sega SG-1000, that predecessor of Master System. Its roms use the extension '.sg'.

But since current wrapper doesn't have that wrapper, we can't run SG-1000 games with installer.
SG-1000 games can playable on real Master System, but current Master System wrapper for RG350 can only read '.sms' extension.

Please add OPK wrapper for SG-1000.

* Edit: Also, Famicom Disk System also wanted for .OPK wrapper. It uses extension '.fds' and can run with FCEUmm core.

**Comment by eduardofilo** [comment]
I had the intention to add it, but I forgot it. I will try to add SG-1000 this weekend. Thanks for the recommendation.

**Comment by eduardofilo** [comment]
Solved in f7b19e9

**Comment by eduardofilo** [comment]
Solved in f7b19e9.
